version: '2'
services:
  enphaseCollector:
    image: "dlmcpaul/enphasecollector:latest"
    container_name: enphaseCollector
    depends_on:
      - db
    networks:
      - internal
    ports:
      - "8080"
    env_file:
      - ./compose.env
    environment:
      SPRING_PROFILES_ACTIVE: influxdb
      ENVOY_INFLUXDBRESOURCE_HOST: db
      ENVOY_INFLUXDBRESOURCE_PORT: 8086
      ENVOY_CONTROLLER_PASSWORD:
  db:
    image: "influxdb:latest"
    container_name: enphaseCollectorDB
    networks:
      - internal
    expose:
      - "8086"
    ports:
      - "8086"
networks:
  internal:
  default:
    external:
      name: bridge
